language: java
jdk:
- openjdk8

addons:
    sonarcloud:
    organization: "lorenzorossi02"
    token:
        secure: 6f8595684658b7088356d101e0fad27a4db86471
script: 
    - ant build 
    - sonar-scanner
