language: java
jdk:
- openjdk8

addons:
    sonarcloud:
    organization: "lorenzorossi02"
    token:
        secure: a4d4a26291d34dc011b43e73b844f69cc287667a
script: 
    - ant build 
    - sonar-scanner
